---
variables:
  MAJOR: "0"
  MINOR: "0"
  ID: $CI_PIPELINE_ID
  VERSION: $MAJOR.$MINOR.$ID

stages:
  - module-pipelines

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $RUN_PIPELINE == "backend"
    - if: $RUN_PIPELINE == "all"
    - changes:
        - "backend/*.md"
        - "backend/Dockerfile"
        - "backend/.gitlab-ci.yml"
        - "backend/.dockerignore"
      when: never
    - changes:
        - backend/**/*

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $RUN_PIPELINE == "frontend"
    - if: $RUN_PIPELINE == "all"
    - changes:
        - "frontend/*.md"
        - "frontend/Dockerfile"
        - "frontend/.gitlab-ci.yml"
        - "frontend/.dockerignore"
      when: never
    - changes:
        - frontend/**/*

